### ISSUE TITLE
Invalid Username/Password while configuring Jenkins

### ISSUE THREAD

**Issue by bzon** [jenkinsci/testrail-plugin#1]
Currently using **Jenkins 2.7.4.**

**How to re-produce:** . 
1. Create a trial account in http://www.gurock.com/testrail/.
2. Clone the git project, build and install the plugin (.hpi).
3. Restart Jenkins.
4. Configure Test Rails Notifier plugin in *Configure System*.
5. ERROR: You get invalid user/password combination error.

<img width="642" alt="testrail1" src="https://cloud.githubusercontent.com/assets/19391568/22001850/43714d5c-dc50-11e6-9118-d58143165f5f.png">
<img width="837" alt="testrail2" src="https://cloud.githubusercontent.com/assets/19391568/22001851/43bd1c32-dc50-11e6-9eaa-5d408b15d4bf.png">

**Comment by xirsoi** [comment]
Can you please provide a screenshot of the configuration and error you are seeing? Feel free to black out anything you don't want to share.

**Comment by bzon** [comment]
Hi @xirsoi , I've updated my issue description and uploaded the screenshots.

**Comment by xirsoi** [comment]
Thanks, I'll get on this as soon as I can.

**Comment by lvryasaswi** [comment]
I have been banging my head (trying to find a workaround) with this issue. I just keep getting 500 when I try to access "http://<hostname>/testrail/index.php?/auth/login". This bug is a real blocker to use this plugin, @xirsoi any luck working on this issue.

**Comment by xirsoi** [comment]
I apologize, but I've been completely swamped at work for two weeks. This is the first time I've had a chance to do anything other than work, eat, or sleep.

I'm going to begin investigating now, to help me, could you let me know what version of Jenkins you are using?

**Comment by xirsoi** [comment]
Try using the email assigned to the TestRail account you are authenticating with.

**Comment by lvryasaswi** [comment]
@xirsoi I figured out what was going wrong. It was the URL that should be exactly as mentioned in "site settings -> Web Address".

**Comment by xirsoi** [comment]
Closing this issue
