### ISSUE TITLE
Failure Messages are not being Posted to TestRail

### ISSUE THREAD

**Issue by arunaousula9421** [jenkinsci/testrail-plugin#10]
```
<testcase classname='DaftUITests.Price' name='testSearchForm_Prices_AnyMin_RandomMax_Category_ToRent_Sharing_Parking'>
      <failure message='XCTAssertEqual failed: (&quot;[&quot;€110/week&quot;]&quot;) is not equal to (&quot;[&quot;From €110/week&quot;]&quot;) - '>Price.swift:185</failure>
    </testcase>
```
Above piece is from a junit which has Failure Message that is not being in TestRail. It is only Posting the message which is between <failure></failure>.
Is there any way we can get the message as well posted into TestRail.
`message='XCTAssertEqual failed: (&quot;[&quot;€110/week&quot;]&quot;) is not equal to (&quot;[&quot;From €110/week&quot;]&quot;) -`

**Comment by xirsoi** [comment]
Probably, I'll look into it this weekend.

**Comment by xirsoi** [comment]
What do you think would be the best way to transmit both values?

**Comment by xirsoi** [comment]
@arunaousula9421 Give the develop branch a try and see if that works for you. Turned out to be a lot simpler than I first thought :p

**Comment by arunaousula9421** [comment]
Thank You @xirsoi I will give it a try

**Comment by arunaousula9421** [comment]
Hi @xirsoi I have tried this with latest develop branch .. It is still the same.. It is only posting `Price.swift:185`. It is not posting `message='XCTAssertEqual failed: (&quot;[&quot;€110/week&quot;]&quot;) is not equal to (&quot;[&quot;From €110/week&quot;]&quot;) - '`

**Comment by arunaousula9421** [comment]
@xirsoi It is working as expected. Thanks for fixing this.

**Comment by xirsoi** [comment]
Done and applied to the master branch.
