### ISSUE TITLE
Field :results.elapsed is not in a valid time span format

### ISSUE THREAD

**Issue by VonC** [jenkinsci/testrail-plugin#12]
When a test last less than a second, The `Result` object has an `elapsed` time of 0.

But https://github.com/jenkinsci/testrail-plugin/commit/214780de8f6ed2766ddc44773a906032fe9d7db5 will make the plugin fail with the error message

    Field :results.elapsed is not in a valid time span format

No other test result is published after the first one with an elapsed time 0 makes the plugin fail.

The older patch avoided correctly to return 0: https://github.com/jenkinsci/testrail-plugin/commit/f774831153a34328e739e99a2bd5b1b7be5c77fc but it was invalidated by the more recent "fix".

PR is coming.

**Comment by xirsoi** [comment]
Fixed
