### ISSUE TITLE
Installing this plugin to Jenkins - does not appear in the list and there is no .hpi for import?

### ISSUE THREAD

**Issue by IantoMcGuckin** [jenkinsci/testrail-plugin#16]
I would really like to use this plugin, but the instructions say to install from Jenkins plugin manager, yet is does not appear in the list of plug-ins.  I can't see any public .hpi file which could be imported in the Jenkins plug-in manager either.

How can I install this?

**Comment by xirsoi** [comment]
I apologize, I last updated those instructions right before I made my first attempts at getting the plugin uploaded. I'm unable to actually upload the plugin for some reason, despite trying for weeks. Until I can get some assistance from others in the Jenkins community the plugin must be installed manually. You'll also have to build it yourself.

I'm sorry for this inconvenience and I will update the instructions momentarily.

**Comment by xirsoi** [comment]
Instructions in ReadMe have been updated.

**Comment by IantoMcGuckin** [comment]
Hi - would it be possible to send me a built .hpi?  I don't have a maven setup for building?

**Comment by xirsoi** [comment]
Sure, I can do that. I'll put it in a dropbox or something and leave a link in this issue.

**Comment by IantoMcGuckin** [comment]
Great, thanks!

**Comment by xirsoi** [comment]
Here ya go!

https://www.dropbox.com/s/tr1eaygt1j47xpj/testrail.hpi?dl=0

Happy testing!

**Comment by thomastruongsb** [comment]
Hello,  can some one send me testrail.hpi?
