### ISSUE TITLE
Error publishing results from Jenkins to TestRail - Field :results.version is a required field

### ISSUE THREAD

**Issue by IantoMcGuckin** [jenkinsci/testrail-plugin#17]
Using the latest versions (Jenkins (2.63), TestRail v5.3.0.3603, and the testrail plugin (today - the .kpi was kindly created for me)), got this error:

Error pushing results to TestRail
Posting to index.php?/api/v2/add_results_for_cases/162 returned an error! Response from TestRail is: 
{"error":"Field :results.version is a required field."}

**Comment by xirsoi** [comment]
It would seem you have Version as a required field and the plugin isn't sending that. As a temporary fix, remove the Version requirement from results. I'll see if anything can be done by the plugin to resolve this.

**Comment by xirsoi** [comment]
Version isn't a part of results, but I could have it send the Milestone if it's been set. How about that?

**Comment by xirsoi** [comment]
I've got a beta, if you're willing to test it. https://www.dropbox.com/s/tr1eaygt1j47xpj/testrail.hpi?dl=0

**Comment by IantoMcGuckin** [comment]
Hi - I'm in the UK ... so on UK time - but I can try this before going to bed ...

**Comment by IantoMcGuckin** [comment]
Hi, updated the plugin (uploaded it again, Jenkins said it was updated and that I should restart Jenkins, which I did -  so I didn't delete it and re-add it).  Set a milestone in testrail and selected this in jenkins.  Same error:

Error pushing results to TestRail
Posting to index.php?/api/v2/add_results_for_cases/165 returned an error! Response from TestRail is: 
{"error":"Field :results.version is a required field."}

![jenkins](https://cloud.githubusercontent.com/assets/29099191/26658106/e9a3de1e-465f-11e7-80d7-b0d46821e9a9.PNG)

**Comment by IantoMcGuckin** [comment]
Same error whether I use the milestone or not

**Comment by xirsoi** [comment]
Thanks for testing it. I'll try again and get back to you when I figure it out.

**Comment by IantoMcGuckin** [comment]
Request for admin access is refused

**Comment by IantoMcGuckin** [comment]
Any progress on this?  Really eager to implement and test!

**Comment by xirsoi** [comment]
I apologise, I didn't have time to work on it this weekend. I will work on it today.

**Comment by IantoMcGuckin** [comment]
Hi, after having a conversation with an admin of TestRail, it has become apparent that we would benefit from being able to specify, possibly a list of, api name/value pairs where the value would be a variable defined in the environment variables of the test run.

For example 

version=7.3.0.7  (changeable, but available as a test run environment variable)
something=something_else_we_want_to_add_in_the_future

Does that sound do-able?

**Comment by xirsoi** [comment]
That is definitely doable, although I'm confused why the Milestone idea didn't work.
I'll do some work to implement this change this week.

**Comment by IantoMcGuckin** [comment]
Hi, any progress on this?

**Comment by xirsoi** [comment]
I'm sorry, I haven't been able to make progress on this. I'm planning to spend some time this weekend on it though.

**Comment by IantoMcGuckin** [comment]
Hi there - I'm under a bit of pressure to be able to show something soon, and I have another meeting at 16:00 BST today with my line manager, so I just need to keep them informed of whether we can use this solution or whether we need to look at something else, I appreciate that it is not a paid (supported) solution - but any progress you can make will be greatly appreciated ;-)

**Comment by xirsoi** [comment]
I've figured out the how and I'll be working on it today after work. I apologise for the time pressure.

**Comment by IantoMcGuckin** [comment]
Hi - did you manage to get some time to look at this?

**Comment by xirsoi** [comment]
Yeah. My initial idea didn't work out (involved an over complicated interface for adding parameters), so the input is going to be a simple string field and it'll expect a JSON object.

It took me longer than I expected to find a good (and up-to-date) Java library for translating json into a hashmap, but I found one last night. Hopefully I can finish this soon. I have Thursday and Friday off of work, so at the very least I'll have it done on Thursday.

**Comment by IantoMcGuckin** [comment]
I've set myself up a new installation of TestRail so I'm the admin.  I've pointed our Jenkins job at the new test TestRail server and verified that everything works fine with the version of the plugin you sent me.  So this has at least proven that it is the new mandatory results.version field that is holding us back in the production environment, and everything should be good when we can specify additional name/value pairs in the plugin.  I can try out various operations.  I have the test environment available for 30 days, beginning from yesterday, so I can trial whatever. 

Would you be open to any further developments after this issue has been resolved? e.g. possibility of being able to publish different report formats - like .trx created by msbuild?  

![trx](https://user-images.githubusercontent.com/29099191/27177001-cf254236-51bc-11e7-974d-ea7deb7ef043.PNG)

**Comment by IantoMcGuckin** [comment]
I've found a way of using an xsl file and msxsl.exe to convert msbuild .trx files to .xml format which import to my staging environment testrail install using your plugin just fine

**Comment by IantoMcGuckin** [comment]
Apart from the fact that I need to then parse the converted xml file and remove the autogenerated datetime from the test name, else testrail thinks that every test run contains new tests, and so the number of tests run and pass/fail diminish while the total number of tests increases

**Comment by IantoMcGuckin** [comment]
Any progress?

**Comment by IantoMcGuckin** [comment]
Any progress?

**Comment by xirsoi** [comment]
I have a prototype on [this branch](https://github.com/jenkinsci/testrail-plugin/tree/feature/%2316). I can't test it on my dev machine easily, but I'll try to tomorrow. I'll update the hpi link I sent earlier, in case you have the opportunity to test it before I do.

You'll see a new field in the per-job configuration for the plugin that lets you add a Json formatted object. The help-blob gives an example of how to use it.

**Comment by IantoMcGuckin** [comment]
Hi, I've downloaded using the link

**Comment by xirsoi** [comment]
Sorry, I didn't see the second part of your message earlier. I'll take a look today after work. Hopefully I have something for you by the time you get to work ;)

**Comment by IantoMcGuckin** [comment]
Another issue I had is where tests are in error, TestRail does not seem to do anything with that information.  So where we had an xml file containing, e.g.,

 <testsuite errors="4" failures="0" name="persistenceTest.CSVDBTest-20170615194206" skipped="0" tests="4" time="0.002">
...
Then TestRail would not report any errors, and it looked as though tests were missing.
My solution was to write some python to process the xml file (the complete solution, including all comments above, is shown below):

 - strip out the datetime from the names of the tests (if present)
 - extract the number of errors and add these to the number of failures
 - change the <error> tags to <failure>
and then nearly everything seemed to work (I still have 3 tests unaccounted for as the time of writing this)

def stripDatetimeFromTestSuiteName(self, xmlFileIn, xmlFileOut):
    for line in open(xmlFileIn,'r'):
        line = re.sub('-201[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]','', line)
        line = re.sub('<error>','<failure>', line)
        line = re.sub('<error message','<failure message', line) 
        line = re.sub('</error>','</failure>', line)
        if 'errors=' in line and 'errors="0"' not in line:
                line = replaceErrorsWithFailures(self, line)
        newFile.write(line)           
            
def replaceErrorsWithFailures(self, xmlLine):
        errors = 0
        failures = 0
        lineBeginsWith = '\t<testsuite '   
        line = xmlLine.split(lineBeginsWith)
        for fields in line:
            if 'errors=' in fields:
                foundErrors = fields.split('" ')
                for splitFields in foundErrors:
                    fieldnames = splitFields.split('="')
                    if 'errors' in fieldnames[0]:
                        errors=int(fieldnames[1])
                    if 'failures' in fieldnames:
                        failures=int(fieldnames[1])
        stringOne = 'failures="' + str(failures)
        stringTwo = 'failures="' + str(failures + errors)
        line = re.sub(stringOne,stringTwo, xmlLine)
        return line

This processing of the xml files gives me really nice, consistent TestRail views for all tests that are in error or have failed.

**Comment by xirsoi** [comment]
Try this hpi file https://www.dropbox.com/s/d01wswume9evld9/testrail.hpi?dl=0

I'll also look into reporting Errors as Failures.

**Comment by IantoMcGuckin** [comment]
Deleted the old config from the job. deleted the old version of the plugin, deleted the config from the filesystem, started cleanly.

Just opening the job and adding the post build action for testrail and saving the job, I get:

org.kohsuke.stapler.WrongTypeException: Got type array but no lister class found for type class java.lang.String
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:723)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:478)
	at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:777)
Caused: java.lang.IllegalArgumentException: Failed to convert the extraParams parameter of the constructor public org.jenkinsci.plugins.testrail.TestRailNotifier(int,int,java.lang.String,java.lang.String,boolean,java.lang.String)
	at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:779)
	at org.kohsuke.stapler.RequestImpl.access$200(RequestImpl.java:83)
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:678)
Caused: java.lang.IllegalArgumentException: Failed to instantiate class org.jenkinsci.plugins.testrail.TestRailNotifier from {"testrailProject":"1","testrailSuite":"34","junitResultsGlob":"unitTestsConverted.xml, cs.unittests.xml, cpp.unittests.xml, OCR.unittests.xml","enableMilestone":true,"testrailMilestone":"1","extraParams":[false,""],"stapler-class":"org.jenkinsci.plugins.testrail.TestRailNotifier","$class":"org.jenkinsci.plugins.testrail.TestRailNotifier"}
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:680)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:478)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:474)
	at hudson.model.Descriptor.newInstance(Descriptor.java:592)
Caused: java.lang.Error: Failed to instantiate class org.jenkinsci.plugins.testrail.TestRailNotifier from {"testrailProject":"1","testrailSuite":"34","junitResultsGlob":"unitTestsConverted.xml, cs.unittests.xml, cpp.unittests.xml, OCR.unittests.xml","enableMilestone":true,"testrailMilestone":"1","extraParams":[false,""],"stapler-class":"org.jenkinsci.plugins.testrail.TestRailNotifier","$class":"org.jenkinsci.plugins.testrail.TestRailNotifier"}


Whatever I do I get the above error.

**Comment by IantoMcGuckin** [comment]
Also to note: in Jenkins,  with each of the plugins I've tried yet, after configuring the system options, when I first add the post build action for TestRail to any job, the selection boxes for the Suite and Milestone are empty.  Have to Save the job and then return to the configuration again where they get populated.  Can they not be populated first time?  Happens every time I add the action to any job (config, list boxes empty, save, config, list boxes populated)

**Comment by IantoMcGuckin** [comment]
I've also had this feedback from my line manager:

3. One thing to note, it looks like the code only identifies Test CASES and does not work with TESTS. Looking at the TestRail API doc on results, (http://docs.gurock.com/testrail-api2/reference-results ) it clearly delineates methods for results for Tests vs Cases. My concern with this is that I’d like to be able to have test IDs associated with different releases. I don’t know TestRail well enough to know what happens if we never use the TestID vs CaseID for results reporting. Can you do the following experiment to see what happens:
1. Take one of your test suites/runs and execute it for 3 build/runs
a. Verify that it does NOT create new/unique tests for each run. (i.e. NO new Test ID # s for each run)
b. Verifying that each result appears as multiple results of the same test run (this is the desired behavior)
c. Then check the CASEs —from Test Suites & Cases tab, verify that there are only the results expected from the righthand Tests & Results
2. Close the test run that has the 3 build/runs data (the Lock Icon at the top of the Test Run view)
3. Then Run the build tests again to verify that new Test ID #’s are generated 
a. If this does not seem correct to you, please hold off on pointing to Production until we can figure a consistent way of using TestRail for all the projects.
(right now I’m opening to have Test Plans and Runs closed as part of the release process so that the data is preserved and we have “new” starting point)

So, after trying to above, I can see that, for every run, we are creating new test IDs for the same test:

![testid](https://user-images.githubusercontent.com/29099191/27325635-fceb7dc4-55a0-11e7-8451-2717ed57ff0d.PNG)

The test has 3 different IDs, one per run.

**Comment by xirsoi** [comment]
I think I know what to do about the error you are seeing when configuring the job. Jelly files are weird.

As for Tests vs Cases, I'm aware of the distinction, and the current behavior of the plugin is as designed. It creates a new Test Run and applies results to that. Test Cases are like the definition of a class, a blueprint. Tests are the implementation of that blueprint.

I may be able to add an optional Test Run Id to post results to, instead of creating a new run, but that will not be an easy task as the code is very messy and hard to modify.

Please do add new issues for these other things.

**Comment by IantoMcGuckin** [comment]
Ok, opened 3 other issues. Will consider this one just for the new extra json paras.

**Comment by IantoMcGuckin** [comment]
Please let me know when a fix is available, thanks

**Comment by IantoMcGuckin** [comment]
Hi, do you have a fix for the jelly file?

**Comment by IantoMcGuckin** [comment]
Is there a timescale for a fix?

**Comment by xirsoi** [comment]
I'm sorry but I can't give any specifics. This project is the first time I've used Java in 6 years, and I've never done anything with jelly files, so I'm learning as I go.

I'm planning to spend a lot of time working on this tomorrow though, so I hope to get something accomplished.

**Comment by IantoMcGuckin** [comment]
Hi, any progress

**Comment by xirsoi** [comment]
Unfortunately no. I've got multiple large projects at work taking up my time. I will be spending every spare minute working on these issues, however. If you have any devs on your team that could help, that would be great.

**Comment by IantoMcGuckin** [comment]
Hi - is there any information you can provide on how to setup a dev env to be able to edit and compile the source?  What tools required, etc.?

**Comment by xirsoi** [comment]
Install the Java SDK and Maven, from there you should be able to follow the instructions in the Read Me. If you have trouble, the Jenkins and Maven documentation will likely prove useful.

**Comment by IantoMcGuckin** [comment]
Hi, it will take while for any of us to get up to speed with doing any work here, so any progress you can make will be greatly appreciated ;-)

**Comment by xirsoi** [comment]
Of course. I will be busy until Monday, when I can dedicate a couple hours to this.

**Comment by IantoMcGuckin** [comment]
Closed as covered by another issue (#17)
