### ISSUE TITLE
Unable to link specific testng tests to specific testrails tests

### ISSUE THREAD

**Issue by totterfree** [jenkinsci/testrail-plugin#18]
I am trying to get this plugin set up with my environment for the first time, so I'm sure there is something I'm missing. I am also sure something should be added to the readme regarding this seemingly simple step since I've read over it quite a few times. How do I go about linking my automated test cases to my testrails tests (presumably by test ID)? I was assuming it could be set via jenkins configuration, but it does not seem to work that way. I also receive the following error after every test which is configured with the plugin as described in the readme. I believe it is indicative of my problem. 

`Uploading results to TestRail.
Error pushing results to TestRail
Posting to index.php?/api/v2/add_results_for_cases/851 returned an error! Response from TestRail is: 
{"error":"Field :results cannot be empty (one result is required)"}
Build step 'TestRail Plugin' marked build as failure`

**Comment by xirsoi** [comment]
Could you please attach the results file your tests generated?

**Comment by xirsoi** [comment]
Also, they are linked by name. I'll make that clear in the readme.

**Comment by xirsoi** [comment]
Aha, this version of the plugin doesn't support TestNG files yet. There is a fork (here)[https://github.com/martin1yness/testrail-jenkins-plugin] that does however.

Right now only xUnit format is supported, though I plan to implement TestNG in the future. I'll update the Read Me to make this clear as well.

**Comment by totterfree** [comment]
Much appreciated!
