### ISSUE TITLE
Report errors as failures

### ISSUE THREAD

**Issue by IantoMcGuckin** [jenkinsci/testrail-plugin#22]
Another issue I had is where tests are in error, TestRail does not seem to do anything with that information. So where we had an xml file containing, e.g.,

<testsuite errors="4" failures="0" name="persistenceTest.CSVDBTest-20170615194206" skipped="0" tests="4" time="0.002">
...
<error message="__init__() takes exactly 8 arguments (7 given)" type="TypeError">

TestRail would not report any errors with the above xml file, and it looked as though tests were missing.
My solution was to write some python to process the xml file (the complete solution, including all comments above, is shown below):

strip out the datetime from the names of the tests (if present)
extract the number of errors and add these to the number of failures
change the <error> tags to <failure>
and then nearly everything seemed to work (I still have 3 tests unaccounted for as the time of writing this)
def stripDatetimeFromTestSuiteName(self, xmlFileIn, xmlFileOut):
    for line in open(xmlFileIn,'r'):
        line = re.sub('-201[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]','', line)
        line = re.sub('<error>','<failure>', line)
        line = re.sub('<error message','<failure message', line) 
        line = re.sub('</error>','</failure>', line)
        if 'errors=' in line and 'errors="0"' not in line:
                line = replaceErrorsWithFailures(self, line)
        newFile.write(line)           
            
def replaceErrorsWithFailures(self, xmlLine):
    errors = 0
    failures = 0
    lineBeginsWith = '\t<testsuite '   
    line = xmlLine.split(lineBeginsWith)
    for fields in line:
        if 'errors=' in fields:
            foundErrors = fields.split('" ')
            for splitFields in foundErrors:
                fieldnames = splitFields.split('="')
                if 'errors' in fieldnames[0]:
                    errors=int(fieldnames[1])
                if 'failures' in fieldnames:
                    failures=int(fieldnames[1])
    stringOne = 'failures="' + str(failures)
    stringTwo = 'failures="' + str(failures + errors)
    line = re.sub(stringOne,stringTwo, xmlLine)
    return line
On processing the xml file, would achieve this:

<testsuite errors="4" failures="4" name="persistenceTest.CSVDBTest" skipped="0" tests="4" time="0.002">
...
<failure message="__init__() takes exactly 8 arguments (7 given)" type="TypeError">

Which gives me really nice, consistent TestRail views for all tests that are in error or have failed

**Comment by xirsoi** [comment]
This was completed by @alexgbernier with pull request #20
