### ISSUE TITLE
Listener

### ISSUE THREAD

**Issue by swilliz** [jenkinsci/testrail-plugin#28]
Hi,

What listeners can be used to create xml files with comply with the unit-schema?

Thanks

**Comment by xirsoi** [comment]
I have no idea, perhaps some of the users might know?

**Comment by swilliz** [comment]
Hey thanks for replying to me. I figured the developers must have some way to generate the xmls in the junit schema to test with. Do you have any resources you can point me to which do that?

Sam Williams

**Comment by xirsoi** [comment]
I just put a test xml file into the job's workspace. You could run a shell script through jenkins (there's a plugin for that) which downloads a testing file, or something.

Most people are running the MSBuild Plugin, or some other testing related plugin, which has xUnit/jUnit as an option to format the output.

**Comment by xirsoi** [comment]
(This link)[https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd] from the ReadMe takes you to the schema for jUnit.
