### ISSUE TITLE
Am I supposed to be able to install this plugin through my Jenkins server's UI?

### ISSUE THREAD

**Issue by artburkart** [jenkinsci/testrail-plugin#3]
When I search for this plugin, it doesn't show up. Are all users expected to build it? Building it with the instructions in the README was very straightforward and easy, so not a problem. I'm mostly just asking to make sure building the plugin from the repo is the intended installation path.

Cheers

**Comment by xirsoi** [comment]
@artburkart I've had some problems with getting it uploaded to the plugin repository, so for now the only installation path is to build it from source.

I'm glad the process has proven simple and easy, but I'd still like to get it hosted. I'll be taking another crack at it this weekend.

Happy testing!
