### ISSUE TITLE
Failed to generate source file(s)

### ISSUE THREAD

**Issue by vramannasoft** [jenkinsci/testrail-plugin#31]
![screenshot from 2017-11-04 00-48-20](https://user-images.githubusercontent.com/33362774/32400620-654c2952-c128-11e7-96a2-1f1166422bc4.png)

Got this error while attempting to install Testrail plugin with the command mvn package -X. 
Failed to generate source file(s) ~/target/generated-sources/localizer/; non-existing directory. [see screenshot]

Please do suggest, how to solve this

**Comment by vramannasoft** [comment]
Also found out that during localizer is not a directory.
![screenshot from 2017-11-04 00-58-58](https://user-images.githubusercontent.com/33362774/32400717-ad7d248c-c129-11e7-941b-9dfca1860379.png)

**Comment by xirsoi** [comment]
Localizer is a file being executed. It's the thing that is throwing the IOException. 

The stack trace indicates that Jenkins may not be able to create a temporary file on the slave.
Have you checked that there is a temp directory and the Jenkins slave is able to write to it?

**Comment by vramannasoft** [comment]
Thanks! I changed to root re-attempted. It worked.

**Comment by xirsoi** [comment]
Happy to help :)
