### ISSUE TITLE
Updated Jenkins Version

### ISSUE THREAD

**Issue by ejhobbs** [jenkinsci/testrail-plugin#34]
According to the pom.xml in this repo, this plugin is built for Jenkins version 1.651.3. However, I'm currently running version 2.89.2. 

If I change the version, I get dependency errors for jenkins-war:war-for-test. Do I need to change the version for this to work with a newer version of Jenkins, and if I do, how can I resolve this error, since according to the official repo that file no longer exists ( http://repo.jenkins-ci.org/releases/org/jenkins-ci/main/jenkins-war/2.89.2/)

**Comment by xirsoi** [comment]
The plugin has a minimum Jenkins version of 1.651.3, but should run just fine in newer versions of Jenkins.

**Comment by xirsoi** [comment]
I've updated the Jenkins version to the 2.32 LTS and updated it's dependencies. Please let me know if you have further issues.

**Comment by ejhobbs** [comment]
Hi, Thanks. 

I actually ended up forking the project since I wanted to add some functionality (https://github.com/squaredup/testrail-jenkins-plugin) and ended up managing to target it at 2.57,  which appears to be the point at which the structure changes and it will no longer compile, something about a WAR file missing? I'm not well versed in Java projects unfortunately so not really sure how to go about fixing that, however it appears to be working fine now.
