### ISSUE TITLE
Junit errors are not captured as failures , test case is still marked as passed

### ISSUE THREAD

**Issue by musanas** [jenkinsci/testrail-plugin#35]
Hi,
My test produces jUnit xml output file which contains errors and not failures.
i,e These are not assertion failures, these could be any exceptions happened during 
the test

In this case , the testRail plugin do not consider errors and mark corresponding test case as failed in testRail end .
test case is still marked as 'passed', hence the errors are silently getting ignored which looks not good.
Attcached the sample of jUnit xml report file here
[jUnit output xml.txt](https://github.com/jenkinsci/testrail-plugin/files/1897297/jUnit.output.xml.txt)

Thanks
Musaffir

**Comment by xirsoi** [comment]
Fixed a long time ago.
