### ISSUE TITLE
Response from TestRail is:  {"error":"Field :results cannot be empty (one result is required)"}

### ISSUE THREAD

**Issue by michaelseno** [jenkinsci/testrail-plugin#38]
I am using the plugin for Testrail/Jenkins and I followed the instructions but will always encounter this issue. I installed/configure Jenkins locally. 

I was not able to get the resolution from older (closed) threads. maybe someone can help me. Please let me know what info you need. Thanks Alot!
```Recording test results
Test Cases: 
  Test Cases: should return landing page 1st attempt
  Test Cases: should return landing page 2nd attempt
  Test Cases: should return landing page 3rd attempt
  Test Cases: should return landing page 4th attempt
  Test Cases: should return landing page 5th attempt
Munging test result files.
Scanning /Users/Shared/Jenkins/tmp/jenkins7488288884795341319tmp
processing jenkins7488288884795341319tmp
processing result.xml
Uploading results to TestRail.
Error pushing results to TestRail
Posting to index.php?/api/v2/add_results_for_cases/1897 returned an error! Response from TestRail is: 
{"error":"Field :results cannot be empty (one result is required)"}
Build step 'TestRail Plugin' marked build as failure
Finished: FAILURE

**Comment by xirsoi** [comment]
I'd love to see your result.xml file, that would help me figure this out.

Thanks for the report!

**Comment by michaelseno** [comment]
Hi Adam, 

Thank you.. below is the xml result:


```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<testsuites name="Mocha Tests" time="0.03900000000000001" tests="5" failures="0">
<testsuite name="Root Suite" timestamp="2018-05-30T09:06:25" tests="0" failures="0" time="0"></testsuite>
<testsuite name="Server launch test" timestamp="2018-05-30T09:06:25" tests="5" file="/Users/Shared/Jenkins/Home/workspace/ci-sample/test/test.js" failures="0" time="0.03900000000000001">
<testcase name="Server launch test should return landing page 1st attempt" time="0.025" classname="should return landing page 1st attempt"></testcase>
<testcase name="Server launch test should return landing page 2nd attempt" time="0.005" classname="should return landing page 2nd attempt"></testcase>
<testcase name="Server launch test should return landing page 3rd attempt" time="0.003" classname="should return landing page 3rd attempt"></testcase>
<testcase name="Server launch test should return landing page 4th attempt" time="0.003" classname="should return landing page 4th attempt"></testcase>
<testcase name="Server launch test should return landing page 5th attempt" time="0.003" classname="should return landing page 5th attempt"></testcase>
</testsuite>
<testsuite name="Server launch test" timestamp="2018-05-30T09:06:25" tests="5" file="/Users/Shared/Jenkins/Home/workspace/ci-sample/test/test.js" failures="0" time="0.03900000000000001">...</testsuite>
</testsuites>
<testsuites name="Mocha Tests" time="0.03900000000000001" tests="5" failures="0">...</testsuites>

**Comment by xirsoi** [comment]
The issue is that you are sending in two test suites, one with results and one without.
I can look into maybe not sending empty result sets?

**Comment by michaelseno** [comment]
I Tried pushing an xml result (manually removing the extra testsuite) but still having the same problem. below is the xml file I used to forward to testrail plugin

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.128" tests="5" failures="0">
   <testsuite name="Server launch test" timestamp="2018-05-31T02:10:38" tests="5" file="/Users/michaelseno/Documents/mjRepo/lethalbrains/test/test.js" failures="0" time="0.128">
    <testcase name="Server launch test should return landing page 1st attempt" time="0.113" classname="should return landing page 1st attempt">
    </testcase>
    <testcase name="Server launch test should return landing page 2nd attempt" time="0.005" classname="should return landing page 2nd attempt">
    </testcase>
    <testcase name="Server launch test should return landing page 3rd attempt" time="0.003" classname="should return landing page 3rd attempt">
    </testcase>
    <testcase name="Server launch test should return landing page 4th attempt" time="0.003" classname="should return landing page 4th attempt">
    </testcase>
    <testcase name="Server launch test should return landing page 5th attempt" time="0.004" classname="should return landing page 5th attempt">
    </testcase>
  </testsuite>
</testsuites>

**Comment by michaelseno** [comment]
Hi Adam,

I also tried adding pass parameter in each test case but I don't know if its necessary but still the same. just let me know what other information you need. Thanks alot.

```<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.128" tests="5" failures="0">
   <testsuite name="Server launch test" timestamp="2018-05-31T02:10:38" tests="5" file="/Users/michaelseno/Documents/mjRepo/lethalbrains/test/test.js" failures="0" time="0.128">
    <testcase name="Server launch test should return landing page 1st attempt" time="0.113" classname="should return landing page 1st attempt" result="pass">
    </testcase>
    <testcase name="Server launch test should return landing page 2nd attempt" time="0.005" classname="should return landing page 2nd attempt" result="pass">
    </testcase>
    <testcase name="Server launch test should return landing page 3rd attempt" time="0.003" classname="should return landing page 3rd attempt" result="pass">
    </testcase>
    <testcase name="Server launch test should return landing page 4th attempt" time="0.003" classname="should return landing page 4th attempt" result="pass">
    </testcase>
    <testcase name="Server launch test should return landing page 5th attempt" time="0.004" classname="should return landing page 5th attempt" result="pass">
    </testcase>
  </testsuite>
</testsuites>

**Comment by xirsoi** [comment]
Please try this build: https://www.dropbox.com/s/hdp4yo0qk0pexcp/testrail.hpi?dl=0

**Comment by michaelseno** [comment]
Hi Adam, 
Sorry for the late reply. I'm in Asia Pacific Region. I've tried using the build you gave but i'm still having the same error message. Please advice. Thanks

**Comment by xirsoi** [comment]
The plugin is following the jUnit schema, expecting testcase elements inside of testsuite elements. It looks for failure or error elements in the testcase. If it doesn't find any, it assumes the case passed.

Right now, I'm not sure why it's not working for you.

**Comment by michaelseno** [comment]
I see, do you think the issue lies maybe in the jenkins setup? I just set it up locally maybe there are some settings that I need to do or something. Or in testrail as well? Since I tried to curl the api manually but it seems that its stuck doesnt return anything. Did you experience this kind of issue before?

**Comment by michaelseno** [comment]
Hi Adam, I would like to check with you if this xml result can be read by the plugin? It seems that the xml result is not being read properly by the plugin. Please let me know if you need more information. Thanks Alot..

```
<testsuite name="Mocha Tests" tests="5" failures="0" errors="0" skipped="0" timestamp="2018-06-05T09:30:20" time="0.049">
<testcase classname="Mocha Automation" name="should return landing page 1st attempt" time="0.023"/>
<testcase classname="Mocha Automation" name="should return landing page 2nd attempt" time="0.006"/>
<testcase classname="Mocha Automation" name="should return landing page 3rd attempt" time="0.004"/>
<testcase classname="Mocha Automation" name="should return landing page 4th attempt" time="0.003"/>
<testcase classname="Mocha Automation" name="should return landing page 5th attempt" time="0.002"/>
</testsuite>
```

it seems that its searching for the result. by the way how will the test cases from the xml to be mapped in the testrail? I just want to know whats happening in the background. below is the error message by the way.

```
Munging test result files.
Scanning /Users/Shared/Jenkins/tmp/jenkins6450467419091450240tmp
processing jenkins6450467419091450240tmp
processing xunit.xml
Uploading results to TestRail.
Error pushing results to TestRail
Posting to index.php?/api/v2/add_results_for_cases/1962 returned an error! Response from TestRail is: 
{"error":"Field :results cannot be empty (one result is required)"}
Build step 'Send results to Test Rail' marked build as failure
Finished: FAILURE
```

**Comment by xirsoi** [comment]
The plugin uses a javax.xml annotations to create a strongly typed object. Like I said before, after the xml is unmarshalled (deserialized) into objects, the TestRailClient object looks at the test cases to figure out what to send to TestRail.

It's all really straightforward, that's why this is so confusing. I'll have some time on Monday to really look into this and try to reproduce your bug.

**Comment by michaelseno** [comment]
By the way Adam, I was able to resolve the issue. The problem lies on the mapping of the result between jenkins and testrail. My testrail suite has the same testcase name as in my testscript which is how its being mapped but the issue lies in the section name of Testrail that Doesn't match the Test suite being created in the xml thats maybe why its passing an empty result when publishing to testrail. 

By the way. is there a documentation in this plugin on how its being mapped? I think it would be very helpful to know such information so that they can match the script with testrail. because the error being returned is kind of general `Posting to index.php?/api/v2/add_results_for_cases/2052 returned an error! Response from TestRail is: 
{"error":"Field :results cannot be empty (one result is required)"}`

**Comment by xirsoi** [comment]
I'm glad you were able to resolve the issue!

Currently no such documentation exists, I'll work on making something this weekend. Documentation is one of the 12 essential vitamins 😜

**Comment by nareshbandi123** [comment]
HI @michaelseno 
I am also facing similar issue while pushing xml result to testrail from jenkins
Posting to index.php?/api/v2/add_results_for_cases/1656 returned an error! Response from TestRail is: 
{"error":"Field :results cannot be empty (one result is required)"}
ERROR: Build step failed with exception
java.lang.NullPointerException
	at org.jenkinsci.plugins.testrail.TestRailNotifier.perform(TestRailNotifier.java:166)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1835)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)

test suite name in xml and testrail is same, name is SQLDMTestAutomation.
can you please tell me how did you resolve issue in your case.

**Comment by xirsoi** [comment]
His issue was that the section names in Testrail didn't match the test suite in the xml.

**Comment by grzegorzSpiewak** [comment]
Hi @michaelseno, @xirsoi,

I'm facing a similar issue when trying to publish results from testrail for the first time. On Jenkins logs I see the following error
```
Error pushing results to TestRail
Posting to index.php?/api/v2/add_results_for_cases/241758 returned an error! Response from TestRail is: 
{"error":"Field :results cannot be empty (one result is required)"}
```

This is the XML file that I'm trying to publish
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuite failures="0" name="Root Suite" tests="7" skipped="0" time="0.473">
   <testsuite failures="0" name="Cpe-dma - get" tests="7" skipped="0" time="0.47300000000000003" timestamp="2021-06-29T05:07:55" file="/home/jenkins/workspace/cpe-dma-test-qa1-uw2-1/tests-mocha/cpe-dma/dma_get.js">
      <testcase name="should return succesfull response for geo location params inside USA" classname="Cpe-dma - get" time="0.038">
      </testcase>
      <testcase name="should return succesfull response for geo location params inside USA served from cache" classname="Cpe-dma - get" time="0.073">
      </testcase>
      <testcase name="should return succesfull response for geo location params from USA territory" classname="Cpe-dma - get" time="0.019">
      </testcase>
      <testcase name="should return succesfull response with DEFAULT dma for location outside of USA which is not in USA territory" classname="Cpe-dma - get" time="0.275">
      </testcase>
      <testcase name="should return succesfull response with DEFAULT dma if no params passed" classname="Cpe-dma - get" time="0.008">
      </testcase>
      <testcase name="should preffer query geo params over x-user-dma header" classname="Cpe-dma - get" time="0.06">
      </testcase>
      <testcase name="Preconditions: Cpe-dma - get" classname="Cpe-dma - get" time="0">
      </testcase>
   </testsuite>
</testsuite>
```

On testrail level, I only see that only contents of <testsuite> is being published but the <testcases> are missing.

<img width="467" alt="Zrzut ekranu 2021-06-29 o 07 45 07" src="https://user-images.githubusercontent.com/18479150/123743736-f23da480-d8ad-11eb-8c56-ef3559735234.png">

Do you maybe know what I'm missing?

**Comment by xirsoi** [comment]
That isn't valid xUnit formatted XML. This plugin can only read xml that follows the xUnit schema.

**Comment by grzegorzSpiewak** [comment]
@xirsoi 

Thanks for pointing that out. I've tried to use `mocha-xunit-reporter` to generate `xUnit formatted XML`  but still seeing the same error.

This is example of XML which I try to publish
```

<?xml version="1.0" encoding="UTF-8"?>
<assemblies>
  <assembly name="Mocha Tests" time="7.5600000000000005" total="6" failed="0" passed="6" skipped="0" run-date="2021-06-29" run-time="21:20:48">
    <collection name="Cpe-dma - get" total="6" failed="0" passed="6" time="7.5600000000000005" skipped="0">
      <test name="Cpe-dma - get should return succesfull response for geo location params inside USA" time="1.272" result="Pass">
      </test>
      <test name="Cpe-dma - get should return succesfull response for geo location params inside USA served from cache" time="1.227" result="Pass">
      </test>
      <test name="Cpe-dma - get should return succesfull response for geo location params from USA territory" time="1.287" result="Pass">
      </test>
      <test name="Cpe-dma - get should return succesfull response with DEFAULT dma for location outside of USA which is not in USA territory" time="1.421" result="Pass">
      </test>
      <test name="Cpe-dma - get should return succesfull response with DEFAULT dma if no params passed" time="1.174" result="Pass">
      </test>
      <test name="Cpe-dma - get should preffer query geo params over x-user-dma header" time="1.179" result="Pass">
      </test>
    </collection>
  </assembly>
</assemblies>
```

Is that the expected format? If not would you be able to provide a sample of a valid XML file?

Thanks in advance for all your help and time

**Comment by xirsoi** [comment]
It is not, the expected format is like this:

``` xml
<testsuites>
   <testsuite>
      <testcase>
      </testcase>
   </testsuite>
</testsuites>
```

You can find the full xUnit schema specification on the internet.

**Comment by ashrimalivmware** [comment]
Hi @xirsoi ,

Facing the similar issue. The xml is:
<testsuites>
   <testsuite name="Section1" tests="1" failures="0" errors="0" skipped="0" timestamp="2021-07-05T09:30:20" time="0.079>
      <testcase classname="TestAutomation" name="Test1" time="0.006"/>
   </testsuite>
</testsuites>

Section name matches with testrail section.

Posting to index.php?/api/v2/add_results_for_cases/53 returned an error! Response from TestRail is: 
{"error":"Field :results cannot be empty (one result is required)"}
ERROR: Build step failed with exception
java.lang.NullPointerException
	at org.jenkinsci.plugins.testrail.TestRailNotifier.perform(TestRailNotifier.java:166)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:80)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:803)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:752)
	at hudson.model.Build$BuildExecution.post2(Build.java:177)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:697)
	at hudson.model.Run.execute(Run.java:1931)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'TestRail Plugin' changed build result to FAILURE
Build step 'TestRail Plugin' marked build as failure
Finished: FAILURE
