### ISSUE TITLE
{"error":"Field :results cannot be empty (one result is required)"} NPE

### ISSUE THREAD

**Issue by nadezhda-y** [jenkinsci/testrail-plugin#42]
Hello, 
may be this is not a real issue, it could be configuration one. I configure the plugin and TestRail and Jenkins connection it is okey, after run the plugin create test run in TestRail, but it doesnt populate result. I got error: 

Posting to index.php?/api/v2/add_results_for_cases/9173 returned an error! Response from TestRail is: 
{"error":"Field :results cannot be empty (one result is required)"}
ERROR: Publisher org.jenkinsci.plugins.testrail.TestRailNotifier aborted due to exception
java.lang.NullPointerException
	at org.jenkinsci.plugins.testrail.TestRailNotifier.perform(TestRailNotifier.java:166)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:74)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:734)
	at hudson.model.Build$BuildExecution.post2(Build.java:183)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:683)
	at hudson.model.Run.execute(Run.java:1784)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)

My result xml it looks like this:

<Results>
<jelly-properties>...</jelly-properties>
<fixture name="SetJavaProperty" info="database.vendor">...</fixture>
<jellystats>...</jellystats>
<TestCase name="Event Rules (4569936, 4569939)" profile="oracle" filename="file:/app/target/reports/EventRules(4569936,4569939)_0.xml">
<summary successCount="2891" failureCount="0" exceptionCount="0" time="03/08/2018 10:00:45 BST" milliseconds="629728"/>
</TestCase>
<jellystats>...</jellystats>
</suite>
</Results>

Could please give some guidelines? Is it possible to fetch the result from this xml output?

**Comment by xirsoi** [comment]
i don't see any xml

**Comment by xirsoi** [comment]
@sunbabyQ were you able to resolve the issue?

**Comment by Subhist** [comment]
Even I am seeing the same issue.

Also, I have a doubt, does it work with testng-results.xml

**Comment by xirsoi** [comment]
@Subhist This plugin does not support TestNG formatted results. There is a fork somewhere that does, however.

**Comment by 7etrahedral** [comment]
Hi,
this issue occurred to me too.
I got the same error either using junit xml or xunit xml spec.
Is it possible I my xml file is incorrect?



[jenkins-test-results.txt](https://github.com/jenkinsci/testrail-plugin/files/2493040/jenkins-test-results.txt)
[jenkins-test-results-xunit.txt](https://github.com/jenkinsci/testrail-plugin/files/2493041/jenkins-test-results-xunit.txt)

![image](https://user-images.githubusercontent.com/17941268/47173974-a46cf200-d339-11e8-8469-ff62d113343d.png)

**Comment by farmboi** [comment]
Happened across this unfortunately we use TAP::Formatter::JUnit and this won't work either. The JUNIT.XSD schema seems to be way different from this and I am curious if there is a way to make this work following our XML schema instead.

**Comment by xirsoi** [comment]
You could fork the project and modify the JUnit classes to fit your schema instead.

**Comment by xirsoi** [comment]
closed, duplicate
