### ISSUE TITLE
Is there a way to post tests docstrings to Test Rail

### ISSUE THREAD

**Issue by himasimplisafe** [jenkinsci/testrail-plugin#43]
This TestRail plugin is very helpful on jenkins, using it I am posting results to Test Rail.
I have bunch of Python API tests, I just need to post more results to Test Rail like Test case doc strings. I know how to post doc strings using Test Rail API, but I want to use Test Rail plugin on jenkins for this purpose.

**Comment by xirsoi** [comment]
If you can find a way to have doctest output the results in xunit format it would be trivial, but I don't think there's any way for this plugin to make that happen.
