### ISSUE TITLE
Not a Jenkins plugin error

### ISSUE THREAD

**Issue by kdrnaik24** [jenkinsci/testrail-plugin#46]
I tried to add jar into the Jenkins but, I am getting the following error: 
'testrail.jar is not a Jenkins plugin'
I have downloaded the project from this repository. And then executed the "mvn package" command.
After that, I tried to upload jar into Jenkins >> manage plugins >> Advanced option
But I got an error which is I have already mentioned.
Please anyone can tell what went wrong and can provide me the right solution.
Thanks.

**Comment by systemsincode** [comment]
You are using the wrong file.
..from the readme.md:

...This will create the hpi file (found in /testrail-plugin/target), which you can then upload to your Jenkins installation.

**Comment by xirsoi** [comment]
Closing
