### ISSUE TITLE
Transfer results to Testrail run with hierarchical structure

### ISSUE THREAD

**Issue by Vadim2305** [jenkinsci/testrail-plugin#47]
Hello! I have issue with transfering results to Testrail run which have hierarchical structure like that 
![изображение](https://user-images.githubusercontent.com/49556190/63948487-696f3b00-ca81-11e9-9fe7-eb08ce38b6ff.png)
I can transferr all results only like root cases without tree structure. 
![изображение](https://user-images.githubusercontent.com/49556190/63949017-66287f00-ca82-11e9-8921-9a12b8b79e44.png)
Is there a possibility transfer results into Testrail run with tree structure of cases?

**Comment by xirsoi** [comment]
Try ensuring that "create new test cases" is disabled. If that doesn't work then this falls under ticket #15 and is thus a duplicate.

**Comment by xirsoi** [comment]
incorrect or a duplicate
