### ISSUE TITLE
Failed to build project with mvn package 

### ISSUE THREAD

**Issue by hgner** [jenkinsci/testrail-plugin#56]
Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.1:javadoc (default) on project testrail: An error has occurred in JavaDocs report generation: 
[ERROR] Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in http://docs.oracle.com/javase/7/docs/api/ are in the unnamed module.
[ERROR] 
[ERROR] Command line was: /Library/Java/JavaVirtualMachines/jdk-13.0.1.jdk/Contents/Home/bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/Users/hakanguner/CPP/mvn/testrail-plugin-master/target/site/apidocs' dir.
[ERROR]

**Comment by hgner** [comment]
We tried with Java 7 also and could not create hpi file to be uploaded to Jenkins

**Comment by xirsoi** [comment]
I'll look into this as soon as I can.

**Comment by hgner** [comment]
Can you share the hpi to directly upload to jenkins if this is an issue for end-user?

**Comment by xirsoi** [comment]
Try building with Java 8, I'm able to do that successfully.
If you aren't, here's the compiled package: https://www.dropbox.com/s/es9gb2ma7431inf/testrail.hpi?dl=0
