### ISSUE TITLE
TestRail plugin doesn't accept User and Password says Invalid user/password combination

### ISSUE THREAD

**Issue by arunaousula9421** [jenkinsci/testrail-plugin#6]
In Jenkins>>Configure Jenkins, I am adding in Host, User and Password.
When I enter User and Password it says Invalid User/Password Combination for both the fields.
Is there any fix for this. my email id looks something like `abc@daft.ie`

**Comment by jjensen554** [comment]
Must be an admin account on TestRail.

**Comment by arunaousula9421** [comment]
@jjensen554 Thanks for the reply. I have fixed the issue.
Can you tell how can I add in new suite names to my TestRail .. I only have Test Cases tab. I don't have Test Suites and Cases tab

**Comment by jjensen554** [comment]
From the TestRail Admin tab you can select how the project is organized, either as a single repository (2 options) or with Multiple Test Suites. If you select the multiple test suite option you then will have Test Suites and Cases. The TestRail plugin on Jenkins will show "master" or your test suite names depending on the option selected.

**Comment by xirsoi** [comment]
Thanks for helping @jjensen554 !
