### ISSUE TITLE
testrail.hpi gets error

### ISSUE THREAD

**Issue by thomastruongsb** [jenkinsci/testrail-plugin#61]
I'm working on integrating Jenkins with TestRail. I'm trying to install this plugin, but it doesn't work. Could some one help me on this?
https://mvnrepository.com/artifact/org.jenkinsci.plugins/testrail/1.0.2

**Comment by xirsoi** [comment]
Holy forking shirtballs, how did this get on the mvn repo?! I spent *months* trying to get publishing to the archive to work with nothing but errors!

Anyway, that version is pretty old, you might wanna try building the package yourself from the master branch.

**Comment by xirsoi** [comment]
Let me know how it goes!

**Comment by xirsoi** [comment]
Closed for inactivity
