### ISSUE TITLE
Conversion of TestLink test cases to TestRail fomat

### ISSUE THREAD

**Issue by melkhail** [jenkinsci/testrail-plugin#69]
### What feature do you want to see added?

Hi All,

I have an issue when I launch the command `php testlink2testrail.php BarreDeNavigationNouveau.xml BarreDeNavigationNouveauRail.xml` , it generates a new file as I want but whiteout(Test Cases).
`Successfully converted 10 sections and 0 cases`

Can any one help on it plz.

Thank you in advance

Regards,

**Comment by xirsoi** [comment]
I'm sorry, you have the wrong repository. We have no php files here. This is a Jenkins plugin.

**Comment by xirsoi** [comment]
That's still not this repository, you need to go to github.com/gurock/testrail-migrate/

**Comment by melkhail** [comment]
Thank you it's resolved
