### ISSUE TITLE
Null Pointer Exception in getElapsedTimeString

### ISSUE THREAD

**Issue by arunaousula9421** [jenkinsci/testrail-plugin#7]
If any of the Automation script fails. TestRail plugin fails to execute Post Build step with an **Null Point Exception**.

```
java.lang.NullPointerException
	at org.jenkinsci.plugins.testrail.TestRailObjects.Result.getElapsedTimeString(Result.java:48)
	at org.jenkinsci.plugins.testrail.TestRailClient.addResultsForCases(TestRailClient.java:287)
	at org.jenkinsci.plugins.testrail.TestRailNotifier.perform(TestRailNotifier.java:141)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1753)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)
Build step 'Notify TestRail' marked build as failure
```

Here's My Test Report

```
<?xml version='1.0' encoding='UTF-8'?>
<testsuites name='DaftUITests.xctest' tests='23' failures='2'>
  <testsuite name='DaftUITests.CaseA' tests='1' failures='0'>
    <testcase classname='DaftUITests.CaseA' name='testCloseOnboardingScreen' time='18.968'/>
  </testsuite>
  <testsuite name='DaftUITests.City_County' tests='6' failures='1'>
    
    <testcase classname='DaftUITests.City_County' name='testSearchForm_City_County_ResetGeneralAreaOrAreas'>
      <failure message='XCTAssertTrue failed - '>City_County.swift:310</failure>
    </testcase>
  </testsuite>
  <testsuite name='DaftUITests.Price' tests='12' failures='1'>
    <testcase classname='DaftUITests.Price' name='testSearchForm_Prices_RandomMin_AnyMax_Category_ToRent_Sharing_Parking'>
      <failure message='No matches found for Cell'>Price.swift:373</failure>
    </testcase>
  </testsuite>
  
</testsuites>
```

If I refactor the XML file without Failure cases it Posts the results on to TestRail. And mark the Tests as **UnTested**.

Any help here to see the failed test cases as well on TestRail.

**Comment by xirsoi** [comment]
I don't see anything in your report xml that is obviously wrong or strange. I'll investigate this today.

Thank you for the report!

**Comment by arunaousula9421** [comment]
Thanks for getting back @xirsoi.

**Comment by jjensen554** [comment]
Just for comparison here is a simplified working xml:
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
	<testsuite name="BVT Preset" errors="0" skipped="0" tests="1" failures="0" time="0" timestamp="2017-04-17T16:36:38.8471256-07:00" >
		<testcase classname="BVT Preset" name="Ambience" time="0" />
	</testsuite>
</testsuites>

**Comment by xirsoi** [comment]
Currently the plugin assumes that the time attribute is present on all test cases, but that is clearly not the case.

What do you believe would be a good default value in that case? The two obvious choices I can see are making it default to 0, or simply not sending the "elapsed" property to testrail.

**Comment by jjensen554** [comment]
I added a time="0" default in every test case. I would vote for default to 0 if not present.

**Comment by xirsoi** [comment]
Ah, I just remembered that TestRail doesn't allow an elapsed value of zero seconds. The plugin already compensates for that by returning
`Math.max(1, elapsed.intValue())`

I'll go with defaulting to 1 then.
